aim: get familiar with using numpy for basic linear algebra concepts 

In [1]:
import numpy as np 

In [ ]:
# defining numpy arrays vs python lists 
alist = [1,2,3,4,5]
narray = np.array([1,2,3,4])

print(alist)
print(narray)
print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
# algebraic operators on numpy arrays vs python lists 
print(narray + narray)
print(alist + alist)

print(narray * 3)
print(alist * 3)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
# creating matrices as a numpy array of arrays using arrays or lists 
npmatrix1 = np.array([narray, narray, narray])
npmatrix2 = np.array([alist, alist, alist])
npmatrix3 = np.array([narray, [1,1,1,1], narray])

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [6]:
# rows must have the same number of elements otherwise we may see unexpected results 
okmatrix = np.array([[1,2], [3,4]])
print(okmatrix)
print(okmatrix * 2)

badmatrix = np.array([[1,2], [3,4], [5,6,7]])
print(badmatrix)
print(badmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
# multiply each element by 2 and add 1 
result = okmatrix * 2 + 1 
print(result)

# add 2 compatible matrices 
result1 = okmatrix + okmatrix 
print(result1)

# subtract 2 compatible matrices (difference vector)
result2 = okmatrix - okmatrix
print(result2)

# multiply each element by itself 
result3 = okmatrix * okmatrix
print(result3)


[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]


In [9]:
# tranpose matrices 
matrix3x2 = np.array([[1,2], [3,4], [5,6]])
print('original 3x2 matrix')
print(matrix3x2)
print('transposed matrix 2x3')
print(matrix3x2.T)

# transpose operation doesn't affect 1d arays
nparray = np.array([1,2,3,4])
print('\noriginal array')
print(nparray)
print('transposed array')
print(nparray.T)

# can transpose a 1xn matrix 
nparray = np.array([[1,2,3,4]])
print('\noriginal array')
print(nparray)
print('transposed array')
print(nparray.T)

original 3x2 matrix
[[1 2]
 [3 4]
 [5 6]]
transposed matrix 2x3
[[1 3 5]
 [2 4 6]]

original array
[1 2 3 4]
transposed array
[1 2 3 4]

original array
[[1 2 3 4]]
transposed array
[[1]
 [2]
 [3]
 [4]]


In [11]:
# getting the norm of a nparray or matrix 
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1,2], [3,4]])
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

# axis parameter controls te form of the operation 
# axis=0 gets the norm of each column, axis=1 gets the norm of each row 
nparray3 = np.array([[1,1], [2,2], [3,3]])
norm_cols = np.linalg.norm(nparray3, axis=0)
norm_rows = np.linalg.norm(nparray3, axis=1)

print(norm_cols)
print(norm_rows)

5.477225575051661
5.477225575051661
[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [12]:
# dot product between arrays 
nparry1 = np.array([0,1,2,3])
nparray2 = np.array([4,5,6,7])
dot_prod = np.dot(nparray1, nparray2)
print(dot_prod)

norm1 = np.dot(np.array([1,2]), np.array([3,4]))
norm2 = np.dot([1,2], [3,4])
print(norm1, '=', norm2)

60
11 = 11


In [13]:
# sum by columns (axis=0) and rows (axis=1)
nparray2 = np.array([[1,-1], [2,-2], [3,-3]])
sum_cols = np.sum(nparray2, axis=0)
sum_rows = np.sum(nparray2, axis=1)

print('sum by columns: ')
print(sum_cols)
print('sum by rows: ')
print(sum_rows)

sum by columns: 
[ 6 -6]
sum by rows: 
[0 0 0]


In [14]:
# mean by rows and columns 
nparray2 = np.array([[1,-1], [2,-2], [3,-3]])
mean = np.mean(nparray2)
mean_cols = np.mean(nparray2, axis=0)
mean_rows = np.mean(nparray2, axis=1)

print('matrix mean: ')
print(mean)
print('mean by columns: ')
print(mean_cols)
print('mean by rows: ')
print(mean_rows)

matrix mean: 
0.0
mean by columns: 
[ 2. -2.]
mean by rows: 
[0. 0. 0.]


In [16]:
# centering columns of a matrix (remove the column mean to each element inside teh column so the man of the columsn is 0)
nparray2 = np.array([[1,1], [2,2], [3,3]])
nparray_centered = nparray2 - np.mean(nparray2, axis=0)

print('original matrix')
print(nparray2)
print('centered by columns matrix')
print(nparray_centered)
print('new mean by column')
print(nparray_centered.mean(axis=0))

# for row centering, transpose the matrix, center by columns, then transpose the matrix back
nparray3 = np.array([[1,3], [2,4], [3,5]])
nparray3_centered = nparray3.T - np.mean(nparray3, axis=1)
nparray3_centered = nparray3_centered.T 

print('original matrix')
print(nparray3)
print('centered by rows matrix')
print(nparray3_centered)
print('new mean by rows')
print(nparray3_centered.mean(axis=1))

original matrix
[[1 1]
 [2 2]
 [3 3]]
centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
new mean by column
[0. 0.]
original matrix
[[1 3]
 [2 4]
 [3 5]]
centered by rows matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
new mean by rows
[0. 0. 0.]
